language: java
notifications:
  email:
    if: type = cron OR branch = master
    recipients:
      - cferiavi@redhat.com
      - jvilalop@redhat.com
      - pcattana@redhat.com
      - mbrophy@redhat.com
      - mrizzi@redhat.com
    on_success: change
    on_failure: always
jdk:
  - openjdk8

services:
  - docker

install:
  - cp ./configuration/settings.xml $HOME/.m2/settings.xml

jobs:
  include:
    - stage: Test
      env:
        - CAMEL_SPRINGBOOT_TRACING=false
        - LOGGING_LEVEL_ROOT=info
        - ANALYSIS_DATAINTEGRITY_LOG=false
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn test -P coverage,sonar; else mvn test -P coverage; fi'
        - bash <(curl -s https://codecov.io/bash)
    - stage: Test
      env:
        - CAMEL_SPRINGBOOT_TRACING=false
        - LOGGING_LEVEL_ROOT=info
        - ANALYSIS_DATAINTEGRITY_LOG=false
      script:
        - mvn test -PendToEnd


