language: java
notifications:
  email:
    if: type = cron OR branch = master
    recipients:
      - cferiavi@redhat.com
      - jvilalop@redhat.com
      - pcattana@redhat.com
      - mbrophy@redhat.com
      - mrizzi@redhat.com
    on_success: change
    on_failure: always
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: project-xavier
    token: $SONAR_TOKEN


sudo: required

services:
    - docker

# Fix for https://travis-ci.community/t/problematic-docker-compose-version-1-23-1/5362/3
before_install:
  - docker-compose --version
  - docker info
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64 > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker info

install:
  - cp ./configuration/settings.xml $HOME/.m2/settings.xml
  - mvn install -P !fuse-fabric8-docker -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jobs:
  include:
    - stage: Test
      env:
        - CAMEL_SPRINGBOOT_TRACING=false
        - LOGGING_LEVEL_ROOT=WARN
        - ANALYSIS_DATAINTEGRITY_LOG=false
      script:
        - mvn test -Pcoverage -Danalysis.dataintegrity.log=false
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'
        - bash <(curl -s https://codecov.io/bash)


